name: Update gh-pages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - name: Generate preview
        run: node .preview_generator

      - name: Deploy it to GH pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
